### ISSUE TITLE
Wookiee is mis-spelled as Wookie (another e needed)

### ISSUE THREAD

**Issue by NicholasCBrown** [swlegion/swlegion#96]
'unhindererd' instead of 'unhindered' keywords on Bossk, Wookiee Warriors, and Environmental Gear. 'Wookie Warriors' instead of 'Wookiee Warriors.'

**Comment by matanlurey** [comment]
Thanks!

**Comment by NicholasCBrown** [comment]
Sorry I should have been more clear, `Wookiee` is the correct spelling with two E's

**Comment by matanlurey** [comment]
Thanks!
